EXPERIMENT:
  NAME: ""
  TAG: "MLKD,res32x4,res8x4"
  PROJECT: "cifar100_ours"
DISTILLER:
  TYPE: "MLKD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 480
  LR: 0.025
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "deepkd_aug"
  DEEPKD:
    DKD: True
    BETA: 2.0
    DELTA_TOG: 0.075
    DELTA_TCG: -0.075
    DELTA_NCG: 0.05
KD:
  LOSS:
    CE_WEIGHT: 0.5
    KD_WEIGHT: 0.5












































