EXPERIMENT:
  NAME: ""
  TAG: "dkdot,dkd,res34,res18"
  PROJECT: "imagenet_ours"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "DKD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
  LR_COS: True
  TRAINER: "deepkd"
  DEEPKD:
    DKD: True
    DELTA_TOG: 0.075
    DELTA_TCG: -0.075
    DELTA_NCG: 0.05
DKD:
  CE_WEIGHT: 1.0
  ALPHA: 1.0
  BETA: 1.0
  T: 1.0
  WARMUP: 1


