EXPERIMENT:
  NAME: ""
  TAG: "mlkd_ours,res34,res18"
  PROJECT: "imagenet_ours"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "MLKD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.1
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
  LR_POLICY: True
  DKDOT:
    DKD: False
    TOPK: 500
    DELTA_TASK: 0.075
    DELTA_TCKD: -0.075
    DELTA_NCKD: 0.05
KD:
  TEMPERATURE: 1
  LOSS:
    CE_WEIGHT: 0.5
    KD_WEIGHT: 0.5
