EXPERIMENT:
  NAME: ""
  TAG: "kd,resnet32x4,wrn_16_2"
  PROJECT: "cifar100_ours"
DISTILLER:
  TYPE: "KD"
  TEACHER: "resnet32x4"
  STUDENT: "wrn_16_2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "deepkd"
  DEEPKD:
    DKD: False
    DELTA_TOG: 0.075
    DELTA_TCG: -0.1
    DELTA_NCG: 0.075
