EXPERIMENT:
  NAME: ""
  TAG: "crld,res32x4,shuv2"
  PROJECT: "cifar100_ours"
DISTILLER:
  TYPE: "CRLD"
  TEACHER: "resnet32x4"
  STUDENT: "ShuffleV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01 
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  LR_COS: True
  TRAINER: "deepkd_aug"
  DEEPKD:
    DKD: True
    BETA: 1.0
    DELTA_TOG: 0.075
    DELTA_TCG: -0.075
    DELTA_NCG: 0.075
CRLD:
  CE_WEIGHT: 1.0
  WV_WEIGHT: 0.5
  CV_WEIGHT: 0.5
